/**
 * AUTO-GENERATED by scripts/generate_wire_types.py
 * DO NOT EDIT — regenerate with: uv run python scripts/generate_wire_types.py -o packages/web/src/lib/api/generated-wire-types.ts
 */

export interface ActiveSessionResponse {
  id: string;
  status: string;
  launcher?: string | null;
  agent_backend: string;
  started_at: string;
  context_window_used?: number | null;
  context_window_size?: number | null;
  cost_amount?: number | null;
  cost_currency?: string | null;
}

export interface ReviewVerdictResponse {
  criterion_index: number;
  verdict: 'PASS' | 'FAIL';
  reason: string;
}

export interface TaskResponse {
  id: string;
  title: string;
  description?: string;
  status: string;
  priority: string;
  base_branch?: string | null;
  repo_id?: string | null;
  acceptance_criteria?: string[];
  agent_backend?: string | null;
  launcher?: string | null;
  review_approved?: boolean;
  review_verdicts?: ReviewVerdictResponse[];
  updated_at?: string | null;
  last_event_at?: string | null;
  has_workspace?: boolean;
  review_running?: boolean;
  active_session?: ActiveSessionResponse | null;
}

export interface TaskSessionResponse {
  id: string;
  launcher?: string | null;
  status: string;
  agent_backend: string;
  started_at: string;
}

export interface ProjectResponse {
  id: string;
  name: string;
  active?: boolean;
}

export interface RepositoryResponse {
  id: string;
  project_id: string;
  name: string;
  path: string;
  default_branch: string;
  selected?: boolean;
}

export interface EventResponse {
  id: string;
  session_id?: string | null;
  type: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface AgentBackendResponse {
  name: string;
  available: boolean;
  reference?: boolean;
}

export interface ChatAgentsResponse {
  backends: AgentBackendResponse[];
  default: string;
}

export interface ChatMessageResponse {
  role: string;
  content: string;
}

export interface ChatSessionSummaryResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
}

export interface ChatSessionResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
  messages: ChatMessageResponse[];
}
