/**
 * AUTO-GENERATED by scripts/generate_wire_types.py
 * DO NOT EDIT — regenerate with: uv run python scripts/generate_wire_types.py -o packages/web/src/lib/api/generated-wire-types.ts
 */

export interface BackendSelectionResponse {
  selected_backend: string;
  backend_confidence: number;
  backend_reason: string;
  alternatives?: string[];
}

export interface ActiveSessionResponse {
  status: string;
  started_at: string;
  id: string;
  launcher?: string | null;
  agent_backend: string;
  agent_role?: string | null;
  context_window_used?: number | null;
  context_window_size?: number | null;
  cost_amount?: number | null;
  cost_currency?: string | null;
}

export interface AcceptanceCriterionResponse {
  id: string;
  task_id: string;
  ordinal: number;
  text: string;
}

export interface ReviewVerdictResponse {
  id: string;
  criterion_id: string;
  session_id?: string | null;
  verdict: 'PASS' | 'FAIL' | 'SKIP';
  reason: string;
}

export interface DiffSummaryResponse {
  files_changed: number;
  additions: number;
  deletions: number;
}

export interface TaskResponse {
  id: string;
  title: string;
  description?: string;
  status: string;
  priority: string;
  base_branch?: string | null;
  repo_id?: string | null;
  github_issue?: string | null;
  acceptance_criteria?: AcceptanceCriterionResponse[];
  agent_backend?: string | null;
  launcher?: string | null;
  review_approved?: boolean;
  updated_at?: string | null;
  last_event_at?: string | null;
  has_workspace?: boolean;
  review_running?: boolean;
  review_verdicts?: ReviewVerdictResponse[];
  active_session?: ActiveSessionResponse | null;
  backend_selection?: BackendSelectionResponse | null;
  diff_summary?: DiffSummaryResponse | null;
}

export interface TaskSessionResponse {
  status: string;
  started_at: string;
  id: string;
  launcher?: string | null;
  agent_backend: string;
  agent_role?: string | null;
}

export interface ProjectResponse {
  id: string;
  name: string;
  active?: boolean;
}

export interface RepositoryResponse {
  id: string;
  project_id: string;
  name: string;
  path: string;
  default_branch: string;
  selected?: boolean;
}

export interface ProjectFolderResolutionResponse {
  path: string;
  repo_path: string;
  suggested_project_name: string;
  is_git_repo: boolean;
  git_root?: string | null;
  existing_project_id?: string | null;
  existing_project_name?: string | null;
  existing_repo_id?: string | null;
}

export interface EventResponse {
  id: string;
  session_id?: string | null;
  type: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface AgentBackendResponse {
  name: string;
  available: boolean;
  reference?: boolean;
}

export interface ChatAgentsResponse {
  backends: AgentBackendResponse[];
  default: string;
}

export interface ChatMessageResponse {
  role: string;
  content: string;
}

export interface ChatMessageDetailResponse {
  id: number;
  session_id: string;
  role: string;
  content: string;
  terminated_at_user_request: boolean;
  created_at: string;
}

export interface ChatSessionSummaryResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
}

export interface ChatSessionResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
  messages: ChatMessageResponse[];
}

export interface TurnInProgressResponse {
  ok?: boolean;
  data?: null;
  error?: string;
  error_code?: string;
  running_since?: string | null;
  partial_chars?: number;
}

export interface DoctorCheckResponse {
  name: string;
  status: string;
  message: string;
  fix_hint: string;
  verify_hint: string;
  category: string;
  is_blocking: boolean;
}

export interface DoctorReportResponse {
  checks: DoctorCheckResponse[];
  ok: boolean;
  fail_count: number;
  warn_count: number;
}

export interface FsEntryResponse {
  name: string;
  path: string;
  is_dir: boolean;
  is_git_repo: boolean;
  is_link: boolean;
}

export interface FsBrowseResponse {
  path: string;
  parent: string | null;
  separator: string;
  roots: string[];
  entries: FsEntryResponse[];
}

export interface IntegrationInfo {
  id: string;
  name: string;
}

export interface IntegrationSyncResult {
  id: string;
  created: number;
  updated: number;
  skipped: number;
  errors?: string[];
}
