from __future__ import annotations

WORKSPACE_MERGE_OVERLAP_PREVIEW_FILE_COUNT = 3
WORKSPACE_MERGE_FAILURE_MESSAGE_MAX_CHARS = 500
WORKSPACE_MERGE_RISK_REPO_CHANGE_THRESHOLD = 1
WORKSPACE_MERGE_RISK_COMMIT_THRESHOLD = 6
WORKSPACE_MERGE_RISK_FILE_THRESHOLD = 12
WORKSPACE_MERGE_RISK_OVERLAP_SCORE = 2
WORKSPACE_MERGE_REBASE_HINT_CAP = 3

__all__ = [
    "WORKSPACE_MERGE_FAILURE_MESSAGE_MAX_CHARS",
    "WORKSPACE_MERGE_OVERLAP_PREVIEW_FILE_COUNT",
    "WORKSPACE_MERGE_REBASE_HINT_CAP",
    "WORKSPACE_MERGE_RISK_COMMIT_THRESHOLD",
    "WORKSPACE_MERGE_RISK_FILE_THRESHOLD",
    "WORKSPACE_MERGE_RISK_OVERLAP_SCORE",
    "WORKSPACE_MERGE_RISK_REPO_CHANGE_THRESHOLD",
]
