/**
 * AUTO-GENERATED by scripts/generate_wire_types.py
 * DO NOT EDIT — regenerate with:
 *   uv run python scripts/generate_wire_types.py -o packages/shared/api-client/src/wire.ts
 */

// ── Domain enums (derived from src/kagan/core/enums.py) ─────────────────────
export type TaskStatus = "BACKLOG" | "IN_PROGRESS" | "REVIEW" | "DONE";
export type SessionStatus = "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
export type Priority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

// ── Event type constants (derived from src/kagan/core/events.py) ────────────
export const EVENT_TYPE = {
  // Chat engine events (kagan.core.events)
  AGENT_LIFECYCLE: "agent_lifecycle",
  ASSISTANT_CHUNK: "assistant_chunk",
  ASSISTANT_MESSAGE_PERSISTED: "assistant_message",
  ERROR: "error",
  THINKING_CHUNK: "thinking_chunk",
  TOOL_CALL: "tool_call",
  TOOL_CALL_RESULT: "tool_call_result",
  TOOL_CALL_UPDATE: "tool_call_update",
  TURN_END: "turn_end",
  TURN_START: "turn_start",
  USAGE_UPDATE: "usage_update",
  USER_MESSAGE_PERSISTED: "user_message",
  // Legacy task session event kinds (persisted in DB by agent runner)
  OUTPUT_CHUNK: "output_chunk",
  TOOL_CALL_START: "tool_call_start",
  AGENT_STATUS: "agent_status",
  TASK_STATUS_CHANGED: "task_status_changed",
  AGENT_COMPLETED: "agent_completed",
  AGENT_FAILED: "agent_failed",
  MERGE_COMPLETED: "merge_completed",
  MERGE_FAILED: "merge_failed",
  CRITERION_VERDICT: "criterion_verdict",
  AUTO_REVIEW_STARTED: "auto_review_started",
  PLAN_UPDATE: "plan_update",
  STEP_VERIFIED: "step_verified",
  CHECKPOINT_CREATED: "checkpoint_created",
  SESSION_REWOUND: "session_rewound",
  HOOK_BLOCKED: "hook_blocked",
  COMPACTION_OCCURRED: "compaction_occurred",
  COMPACTION_TRIGGERED: "compaction_triggered",
  DOCTOR_WARNED: "doctor_warned",
  FIRST_SESSION_SUCCESS: "first_session_success",
  BACKEND_AUTO_PROMOTED: "backend_auto_promoted",
  INSIGHT_EXTRACTED: "insight_extracted",
} as const;

export type EventType = (typeof EVENT_TYPE)[keyof typeof EVENT_TYPE];

export const SSE_TYPE = {
  TASK_UPDATED: "TASK_UPDATED",
  SESSION_EVENT: "SESSION_EVENT",
} as const;

export type SSEType = (typeof SSE_TYPE)[keyof typeof SSE_TYPE];

export const CHAT_WATCH_TYPE = {
  CHAT_USER_MESSAGE: "CHAT_USER_MESSAGE",
  CHAT_ASSISTANT_MESSAGE: "CHAT_ASSISTANT_MESSAGE",
  CHAT_TURN_STARTED: "CHAT_TURN_STARTED",
  CHAT_TURN_TERMINATED: "CHAT_TURN_TERMINATED",
  CHAT_SESSION_UPDATED: "CHAT_SESSION_UPDATED",
  CHAT_ERROR: "CHAT_ERROR",
  CHAT_PERMISSION_REQUEST: "CHAT_PERMISSION_REQUEST",
} as const;

export type ChatWatchType = (typeof CHAT_WATCH_TYPE)[keyof typeof CHAT_WATCH_TYPE];

export const TASK_COLUMNS: TaskStatus[] = [
  "BACKLOG",
  "IN_PROGRESS",
  "REVIEW",
  "DONE",
];

// ── Response models (from src/kagan/server/responses.py) ────────────────────

export interface BackendSelectionResponse {
  selected_backend: string;
  backend_confidence: number;
  backend_reason: string;
  alternatives?: string[];
}

export interface ActiveSessionResponse {
  status: string;
  started_at: string;
  id: string;
  launcher?: string | null;
  agent_backend: string;
  agent_role?: string | null;
  context_window_used?: number | null;
  context_window_size?: number | null;
  cost_amount?: number | null;
  cost_currency?: string | null;
}

export interface AcceptanceCriterionResponse {
  id: string;
  task_id: string;
  ordinal: number;
  text: string;
}

export interface ReviewVerdictResponse {
  id: string;
  criterion_id: string;
  session_id?: string | null;
  verdict: 'PASS' | 'FAIL' | 'SKIP';
  reason: string;
}

export interface DiffSummaryResponse {
  files_changed: number;
  additions: number;
  deletions: number;
}

export interface TaskResponse {
  id: string;
  title: string;
  description?: string;
  status: string;
  priority: string;
  base_branch?: string | null;
  repo_id?: string | null;
  github_issue?: string | null;
  acceptance_criteria?: AcceptanceCriterionResponse[];
  agent_backend?: string | null;
  launcher?: string | null;
  review_approved?: boolean;
  updated_at?: string | null;
  last_event_at?: string | null;
  has_workspace?: boolean;
  review_running?: boolean;
  review_verdicts?: ReviewVerdictResponse[];
  active_session?: ActiveSessionResponse | null;
  backend_selection?: BackendSelectionResponse | null;
  diff_summary?: DiffSummaryResponse | null;
}

export interface TaskSessionResponse {
  status: string;
  started_at: string;
  id: string;
  launcher?: string | null;
  agent_backend: string;
  agent_role?: string | null;
}

export interface ProjectResponse {
  id: string;
  name: string;
  active?: boolean;
}

export interface RepositoryResponse {
  id: string;
  project_id: string;
  name: string;
  path: string;
  default_branch: string;
  selected?: boolean;
}

export interface ProjectFolderResolutionResponse {
  path: string;
  repo_path: string;
  suggested_project_name: string;
  is_git_repo: boolean;
  git_root?: string | null;
  existing_project_id?: string | null;
  existing_project_name?: string | null;
  existing_repo_id?: string | null;
}

export interface EventResponse {
  id: string;
  session_id?: string | null;
  type: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface AgentBackendResponse {
  name: string;
  available: boolean;
  reference?: boolean;
}

export interface ChatAgentsResponse {
  backends: AgentBackendResponse[];
  default: string;
}

export interface ChatMessageResponse {
  role: string;
  content: string;
}

export interface ChatMessageDetailResponse {
  id: number;
  session_id: string;
  role: string;
  content: string;
  terminated_at_user_request: boolean;
  created_at: string;
}

export interface ChatSessionSummaryResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
}

export interface ChatSessionResponse {
  id: string;
  label: string;
  source: string;
  agent_backend?: string | null;
  project_id?: string | null;
  updated_at: string;
  message_count: number;
  messages: ChatMessageResponse[];
}

export interface TurnInProgressResponse {
  ok?: boolean;
  data?: null;
  error?: string;
  error_code?: string;
  running_since?: string | null;
  partial_chars?: number;
}

export interface DoctorCheckResponse {
  name: string;
  status: string;
  message: string;
  fix_hint: string;
  verify_hint: string;
  category: string;
  is_blocking: boolean;
}

export interface DoctorReportResponse {
  checks: DoctorCheckResponse[];
  ok: boolean;
  fail_count: number;
  warn_count: number;
}

export interface FsEntryResponse {
  name: string;
  path: string;
  is_dir: boolean;
  is_git_repo: boolean;
  is_link: boolean;
}

export interface FsBrowseResponse {
  path: string;
  parent: string | null;
  separator: string;
  roots: string[];
  entries: FsEntryResponse[];
}

export interface IntegrationInfo {
  id: string;
  name: string;
}

export interface IntegrationSyncResult {
  id: string;
  created: number;
  updated: number;
  skipped: number;
  errors?: string[];
}

export interface MentionResponse {
  source: string;
  id: string;
  title: string;
  state?: string | null;
}

export interface SessionCapabilitiesResponse {
  can_chat: boolean;
  can_stream: boolean;
  can_replay: boolean;
  can_stop: boolean;
  can_close: boolean;
  has_kagan_tools: boolean;
}

export interface SessionItemResponse {
  id: string;
  type: string;
  role: string | null;
  status: string;
  title: string;
  backend: string | null;
  project_id: string | null;
  task_id: string | null;
  task_status?: string | null;
  session_id: string | null;
  chat_session_id: string | null;
  updated_at: string;
  capabilities: SessionCapabilitiesResponse;
}

export interface SessionsResponse {
  sessions: SessionItemResponse[];
}

export interface CreateSessionRequest {
  type: 'orchestrator' | 'general';
  backend?: string | null;
  title?: string | null;
}

export interface SessionReplayEvent {
  id: string;
  session_id?: string | null;
  event_type: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface SessionReplayPage {
  events: SessionReplayEvent[];
  next_cursor?: string | null;
  has_more?: boolean;
}

export interface TaskCreateRequest {
  acceptance_criteria?: string[] | null;
  title: string;
  description?: string;
  priority?: string | number | null;
  base_branch?: string | null;
  agent_backend?: string | null;
  launcher?: string | null;
  repo_id?: string | null;
  github_issue?: string | null;
}

export interface TaskUpdateRequest {
  acceptance_criteria?: string[] | null;
  title?: string | null;
  description?: string | null;
  priority?: string | number | null;
  base_branch?: string | null;
  agent_backend?: string | null;
  launcher?: string | null;
  repo_id?: string | null;
}

export interface ChatSessionCreateRequest {
  agent_backend?: string | null;
  label?: string | null;
  source?: string;
  project_id?: string | null;
  session_type?: string | null;
}

export interface ChatSessionPatchRequest {
  agent_backend?: string | null;
}

export interface ProjectCreateRequest {
  name: string;
}

export interface RepoAddRequest {
  path: string;
}

export interface ReviewDecideRequest {
  action: string;
  feedback?: string | null;
}

// ── Static wire sections (maintained in scripts/generate_wire_types.py) ──────

// ── Chat engine events (from src/kagan/core/events.py) ───────────────────────
// Discriminated on the ``type`` field.  Emitted by the engine over the /watch
// SSE channel alongside the transport-layer lifecycle frames (which use ``t``).

export interface ChatEventTurnStart {
  type: "turn_start";
  turn_id: string;
  session_id: string;
  agent_id: string;
}
export interface ChatEventTurnEnd {
  type: "turn_end";
  turn_id: string;
  reason: "done" | "cancelled" | "error" | "max_turns" | "refusal" | "permission_denied";
}
export interface ChatEventAssistantChunk {
  type: "assistant_chunk";
  turn_id: string;
  session_id: string;
  message_id: string;
  delta: string;
}
export interface ChatEventThinkingChunk {
  type: "thinking_chunk";
  turn_id: string;
  session_id: string;
  message_id: string;
  delta: string;
}
export interface ChatEventToolCall {
  type: "tool_call";
  turn_id: string;
  session_id: string;
  tool_call_id: string;
  name: string;
  args: string | null;
  title: string;
  kind: string | null;
}
export interface ChatEventToolCallUpdate {
  type: "tool_call_update";
  tool_call_id: string;
  content: string | null;
  progress: string | null;
}
export interface ChatEventToolCallResult {
  type: "tool_call_result";
  tool_call_id: string;
  output: string | null;
  is_error: boolean;
}
export interface ChatEventUsageUpdate {
  type: "usage_update";
  turn_id: string;
  input: number | null;
  output: number | null;
  cached: number | null;
  cost: number | null;
}
export interface ChatEventError {
  type: "error";
  turn_id: string | null;
  code: string;
  message: string;
  fatal: boolean;
}
export interface ChatEventAgentLifecycle {
  type: "agent_lifecycle";
  session_id: string;
  task_id: string | null;
  kind: "started" | "finished" | "stopped" | "failed";
  detail: string | null;
}
export interface ChatEventAssistantMessage {
  type: "assistant_message";
  message_id: number;
  content: string;
  terminated: boolean;
}
export interface ChatEventUserMessage {
  type: "user_message";
  message_id: number;
  content: string;
}

/** Engine events — discriminated on ``type``. */
export type ChatEngineEvent =
  | ChatEventTurnStart
  | ChatEventTurnEnd
  | ChatEventAssistantChunk
  | ChatEventThinkingChunk
  | ChatEventToolCall
  | ChatEventToolCallUpdate
  | ChatEventToolCallResult
  | ChatEventUsageUpdate
  | ChatEventError
  | ChatEventAgentLifecycle
  | ChatEventAssistantMessage
  | ChatEventUserMessage;

// ── Chat /watch transport-layer lifecycle frames ──────────────────────────────
// These are emitted directly by the server transport (not the engine).
// Discriminated on the ``t`` field.

export interface ChatWatchUserMessage {
  t: "CHAT_USER_MESSAGE";
  message_id: number;
  content: string;
}
export interface ChatWatchAssistantMessage {
  t: "CHAT_ASSISTANT_MESSAGE";
  message_id: number;
  content: string;
  terminated: boolean;
}
export interface ChatWatchTurnStarted {
  t: "CHAT_TURN_STARTED";
  at: string;
  by_source: string | null;
}
export interface ChatWatchTurnTerminated {
  t: "CHAT_TURN_TERMINATED";
  reason: "user" | "takeover" | string;
}
export interface ChatWatchSessionUpdated {
  t: "CHAT_SESSION_UPDATED";
  session: ChatSessionSummaryResponse;
}
export interface ChatWatchError {
  t: "CHAT_ERROR";
  error: string;
}
export interface ChatWatchPermissionRequest {
  t: "CHAT_PERMISSION_REQUEST";
  future_id: string;
  tool_name: string;
}

/**
 * All events that can arrive on the GET /api/chat/sessions/{id}/watch SSE channel.
 *
 * Two discriminator keys are in play:
 *   - ``type`` — engine events from ``kagan.core.events`` (ChatEngineEvent union).
 *   - ``t``    — transport-layer lifecycle frames emitted by the server directly.
 *
 * Consumers should handle both.  A narrow switch on ``type`` covers engine
 * events; a switch on ``t`` covers lifecycle frames.
 */
export type ChatWatchEvent = ChatEngineEvent | ChatWatchUserMessage | ChatWatchAssistantMessage | ChatWatchTurnStarted | ChatWatchTurnTerminated | ChatWatchSessionUpdated | ChatWatchError | ChatWatchPermissionRequest;

// ── Chat POST /stream response events ────────────────────────────────────────
// The POST /api/chat/{id}/stream endpoint also uses ``t``-keyed frames for
// compatibility with the orchestrator streaming path.

export interface ChatStreamChunk {
  t: "CHAT_CHUNK";
  content: string;
  thought?: boolean;
}
export interface ChatStreamToolStart {
  t: "CHAT_TOOL_START";
  tool: string;
}
export interface ChatStreamToolProgress {
  t: "CHAT_TOOL_PROGRESS";
  tool: string;
  status: string | null;
}
export interface ChatStreamDone {
  t: "CHAT_DONE";
  full_response: string;
}
export interface ChatStreamError {
  t: "CHAT_ERROR";
  error?: string;
}
export interface ChatStreamSessionUpdated {
  t: "CHAT_SESSION_UPDATED";
  session?: ChatSessionSummaryResponse;
}

export type ChatStreamEvent =
  | ChatStreamChunk
  | ChatStreamToolStart
  | ChatStreamToolProgress
  | ChatStreamDone
  | ChatStreamError
  | ChatStreamSessionUpdated;

/** Abbreviated-key constant map for the POST /api/chat/{id}/stream event types. */
export const CHAT_STREAM_EVENT = {
  CHUNK: "CHAT_CHUNK",
  TOOL_START: "CHAT_TOOL_START",
  TOOL_PROGRESS: "CHAT_TOOL_PROGRESS",
  DONE: "CHAT_DONE",
  ERROR: "CHAT_ERROR",
  SESSION_UPDATED: "CHAT_SESSION_UPDATED",
} as const;

export type ChatStreamEventType = (typeof CHAT_STREAM_EVENT)[keyof typeof CHAT_STREAM_EVENT];

// ── Envelope ─────────────────────────────────────────────────────────────────

/**
 * Generic wrapper for all wire responses.
 * ok=true → data carries payload.
 * ok=false → error carries a human-readable message.
 */
export interface WireEnvelope<T = unknown> {
  ok: boolean;
  data?: T | null;
  error?: string | null;
  error_code?: string | null;
}

// ── SSE envelope types ────────────────────────────────────────────────────────

export interface SSETaskUpdated {
  type: typeof SSE_TYPE.TASK_UPDATED;
  task_id: string;
  /**
   * Inline task payload — present when the server can build it (the common
   * case). Absent on the cross-process DB-poll fallback path; clients should
   * fall back to refetching when it is missing.
   */
  task?: TaskResponse;
}

export interface SSESessionEvent {
  type: typeof SSE_TYPE.SESSION_EVENT;
  task_id: string;
  event: EventResponse;
}

export type SSEMessage = SSETaskUpdated | SSESessionEvent;

// ── Turn status ───────────────────────────────────────────────────────────────

/** Full turn status returned by GET /api/chat/{id}/turn-status */
export interface TurnStatusResponse {
  active: boolean;
  partial_chars: number | null;
  running_since: string | null;
}

// ── Analytics (informal — server returns raw dicts, no Pydantic model) ────────

export interface BackendStats {
  agent_backend: string;
  count: number;
  success_rate: number;
  avg_duration_seconds: number | null;
  retry_rate: number;
}

export interface SessionTimelineEntry {
  date: string;
  total: number;
  completed: number;
  failed: number;
  cancelled: number;
  running: number;
  pending: number;
}

export interface AnalyticsExport {
  exported_at: string | null;
  period_days: number;
  backend_stats: BackendStats[];
  session_timeline: SessionTimelineEntry[];
}

export interface BackendRecommendation {
  backend?: string;
  success_rate?: number;
  count?: number;
}

export interface RoleStats {
  agent_backend: string;
  agent_role: string;
  count: number;
  success_rate: number;
  avg_duration_seconds: number | null;
}

export interface TaskTypeStats {
  agent_backend: string;
  task_type: string;
  count: number;
  success_rate: number;
  avg_duration_seconds: number | null;
}

export interface CombinedStats {
  agent_backend: string;
  agent_role: string;
  task_type: string;
  count: number;
  success_rate: number;
  avg_duration_seconds: number | null;
}

export interface AnalyticsByRole {
  [role: string]: RoleStats[];
}

export interface AnalyticsByTaskType {
  [taskType: string]: TaskTypeStats[];
}

export interface BackendTaskRecommendation {
  backend: string;
  reason: string;
  confidence: number;
  alternatives: string[];
}

// ── Client presence (informal — no Pydantic model) ───────────────────────────

export interface ClientPresence {
  client_id: string;
  client_type: string;
  connected_at: number;
  active_task_id: string | null;
  user_label: string;
}

// ── Client-side diff/worktree/commit shapes (informal) ───────────────────────

export interface DiffStats {
  files_changed: number;
  insertions: number;
  deletions: number;
}

export interface DiffFile {
  path: string;
  status: string;
  insertions: number;
  deletions: number;
}

export interface TaskWorktree {
  path: string;
  branch: string;
}

export interface TaskWorktreeResponse {
  task_id: string;
  worktree: TaskWorktree | null;
}

export interface TaskCommit {
  short_hash: string;
  message: string;
}

export interface TaskCommitsResponse {
  task_id: string;
  branch: string | null;
  base_branch: string;
  commits: TaskCommit[];
}

// ── Simple ad-hoc response shapes ────────────────────────────────────────────

export interface TaskDeletedResponse {
  task_id: string;
  deleted: boolean;
}

export interface ProjectActivatedResponse {
  project_id: string;
  active: boolean;
}

export interface ProjectDeletedResponse {
  project_id: string;
  deleted: boolean;
}

export interface ReviewStatusResponse {
  task_id: string;
  status: TaskStatus | string;
  review_approved: boolean;
}

export interface ReviewDecideResponse {
  task?: TaskResponse;
  task_id?: string;
  action: string;
  reason?: string;
  reason_code?: string;
}

export interface PreflightCheck {
  name: string;
  status: string;
  message: string;
  fix_hint: string | null;
  is_blocking: boolean;
}

export interface PreflightResponse {
  checks: PreflightCheck[];
  ok: boolean;
}

export interface TaskCountsResponse {
  BACKLOG?: number;
  IN_PROGRESS?: number;
  REVIEW?: number;
  DONE?: number;
  [key: string]: number | undefined;
}

export interface WorkflowResolvedSettings {
  wip_limits: Record<TaskStatus, number>;
}

export interface ResolvedSettingsResponse {
  git_user_name: string;
  git_user_email: string;
  dotfile_overrides: Record<string, string | null>;
  workflow: WorkflowResolvedSettings;
  chat_last_active_session?: string;
}

// ── Client configuration ──────────────────────────────────────────────────────

export interface KaganClientConfig {
  baseUrl: string;
  protocol?: "http" | "https";
  token?: string;
  /** Client type identifier for presence/tracking. @default "unknown" */
  clientType?: string;
}

export interface RequestOptions extends Omit<RequestInit, "body"> {
  body?: unknown;
}

// ── Mention autocomplete (informal) ──────────────────────────────────────────

export interface Mention {
  source: "kagan" | "github";
  id: string;
  title: string;
  state: string | null;
}

export interface SearchMentionsInput {
  projectId: string;
  q: string;
  limit?: number;
}

// ── Task event query options ──────────────────────────────────────────────────

export interface TaskEventOptions {
  limit?: number;
  offset?: number;
  tail?: boolean;
  before?: string;
  before_id?: string;
  after?: string;
  after_id?: string;
  session_id?: string;
}

// ── Presence heartbeat input ──────────────────────────────────────────────────

export interface PresenceHeartbeatInput {
  client_id: string;
  client_type: string;
  active_task_id?: string | null;
  user_label?: string;
}

// ── Run task input ────────────────────────────────────────────────────────────

export interface RunTaskInput {
  agent_backend?: string;
  launcher?: string;
  persona?: string;
}

// ── Transition status input ───────────────────────────────────────────────────

export interface TransitionStatusInput {
  status: TaskStatus;
}

// ── Request model aliases (canonical names used in TS clients) ────────────────

export type CreateTaskInput = TaskCreateRequest;
export type UpdateTaskInput = TaskUpdateRequest;
export type CreateChatSessionInput = ChatSessionCreateRequest;
export type CreateProjectInput = ProjectCreateRequest;
/** @deprecated Use ReviewDecideRequest */
export type ReviewDecisionInput = ReviewDecideRequest;

/** Alias for ReviewDecideResponse (legacy naming used by VS Code extension). */
export type ReviewDecisionResponse = ReviewDecideResponse;

// ── Review verdict state ──────────────────────────────────────────────────────

export type ReviewVerdictState = "PASS" | "FAIL" | "SKIP";

// ── Legacy aliases ────────────────────────────────────────────────────────────

/** @deprecated Use ActiveSessionResponse */
export type ActiveSession = ActiveSessionResponse;
/** @deprecated Use ReviewVerdictResponse */
export type ReviewVerdict = ReviewVerdictResponse;
/** @deprecated Use TaskResponse */
export type WireTask = TaskResponse;
/** @deprecated Use TaskSessionResponse */
export type WireTaskSession = TaskSessionResponse;
/** @deprecated Use ProjectResponse */
export type WireProject = ProjectResponse;
/** @deprecated Use RepositoryResponse */
export type WireRepository = RepositoryResponse;
/** @deprecated Use ChatSessionSummaryResponse */
export type WireChatSessionSummary = ChatSessionSummaryResponse;
/** @deprecated Use ChatSessionResponse */
export type WireChatSession = ChatSessionResponse;
/** @deprecated Use EventResponse */
export type WireEvent = EventResponse;
/** @deprecated Use DiffSummaryResponse */
export type WireDiffSummary = DiffSummaryResponse;
/** @deprecated Use AgentBackendResponse */
export type AgentBackend = AgentBackendResponse;
/** @deprecated Use ChatMessageDetailResponse */
export type WireChatMessage = ChatMessageResponse;
/** @deprecated Use FsEntryResponse */
export type FsEntry = FsEntryResponse;
// SettingsResponse is informal — server returns Record<string, string>
export type SettingsResponse = Record<string, string | undefined>;
// Preflight/doctor aliases
export type DoctorCheck = DoctorCheckResponse;
export type DoctorReport = DoctorReportResponse;
