from __future__ import annotations

CHAT_OVERLAY_ORCHESTRATOR_PROMPT_TIMEOUT_SECONDS = 300.0
CHAT_OVERLAY_COMPACT_MAX_HISTORY_ITEMS = 24
CHAT_OVERLAY_COMPACT_ENTRY_MAX_CHARS = 600
CHAT_OVERLAY_COMPACT_SNAPSHOT_MAX_CHARS = 8_000
CHAT_OVERLAY_COMPACT_PREVIEW_MAX_CHARS = 1_200
CHAT_OVERLAY_CHAT_TARGETS_CACHE_TTL_SECONDS = 1.0
CHAT_OVERLAY_SKILL_METADATA_MAX_BYTES = 16_384
CHAT_OVERLAY_SKILL_DESCRIPTION_MAX_CHARS = 220
CHAT_OVERLAY_SKILL_DISCOVERY_MAX_FILES = 256
CHAT_OVERLAY_SKILL_DISCOVERY_DISPLAY_LIMIT = 60
CHAT_OVERLAY_AUTO_STREAM_POLL_FAST_SECONDS = 0.35
CHAT_OVERLAY_AUTO_STREAM_POLL_MEDIUM_SECONDS = 0.75
CHAT_OVERLAY_AUTO_STREAM_POLL_IDLE_SECONDS = 1.5
CHAT_OVERLAY_AUTO_STREAM_RECONCILE_INTERVAL_SECONDS = 2.0

__all__ = [
    "CHAT_OVERLAY_AUTO_STREAM_POLL_FAST_SECONDS",
    "CHAT_OVERLAY_AUTO_STREAM_POLL_IDLE_SECONDS",
    "CHAT_OVERLAY_AUTO_STREAM_POLL_MEDIUM_SECONDS",
    "CHAT_OVERLAY_AUTO_STREAM_RECONCILE_INTERVAL_SECONDS",
    "CHAT_OVERLAY_CHAT_TARGETS_CACHE_TTL_SECONDS",
    "CHAT_OVERLAY_COMPACT_ENTRY_MAX_CHARS",
    "CHAT_OVERLAY_COMPACT_MAX_HISTORY_ITEMS",
    "CHAT_OVERLAY_COMPACT_PREVIEW_MAX_CHARS",
    "CHAT_OVERLAY_COMPACT_SNAPSHOT_MAX_CHARS",
    "CHAT_OVERLAY_ORCHESTRATOR_PROMPT_TIMEOUT_SECONDS",
    "CHAT_OVERLAY_SKILL_DESCRIPTION_MAX_CHARS",
    "CHAT_OVERLAY_SKILL_DISCOVERY_DISPLAY_LIMIT",
    "CHAT_OVERLAY_SKILL_DISCOVERY_MAX_FILES",
    "CHAT_OVERLAY_SKILL_METADATA_MAX_BYTES",
]
