"""Shared Textual theme definition for Kagan."""

from __future__ import annotations

from textual.theme import Theme

KAGAN_THEME = Theme(
    name="kagan",
    primary="#d4a84b",
    secondary="#3fb58e",
    accent="#C27C4E",
    foreground="#FFFFFF",
    background="#0B0A09",
    surface="#151311",
    panel="#1E1B17",
    warning="#e6c07b",
    error="#e85535",
    success="#3fb58e",
    dark=True,
    variables={
        "border": "#2A251F",
        "border-blurred": "#2A251F80",
        "text-muted": "#B5AC9F",
        "text-disabled": "#A9A094",
        "kanban-background": "#0F0E0C",
        "input-cursor-foreground": "#000000",
        "input-cursor-background": "#d4a84b",
        "input-selection-background": "#d4a84b33",
        "scrollbar": "#2A251F",
        "scrollbar-hover": "#d4a84b",
        "scrollbar-active": "#C27C4E",
        "link-color": "#6fa3d4",
        "link-hover-color": "#3fb58e",
        "footer-key-foreground": "#C2B9AD",
        "footer-key-background": "transparent",
        "footer-description-foreground": "#B5AC9F",
        "button-foreground": "#FFFFFF",
        "button-color-foreground": "#000000",
    },
)


KAGAN_THEME_256 = Theme(
    name="kagan-256",
    primary="#d7af5f",
    secondary="#5faf87",
    accent="#d7875f",
    foreground="#ffffff",
    background="#141414",
    surface="#242424",
    panel="#303030",
    warning="#d7af87",
    error="#d75f5f",
    success="#5faf87",
    dark=True,
    variables={
        "border": "#353535",
        "border-blurred": "#35353580",
        "text-muted": "#bdbdbd",
        "text-disabled": "#b0b0b0",
        "kanban-background": "#1e1e1e",
        "input-cursor-foreground": "#000000",
        "input-cursor-background": "#d7af5f",
        "input-selection-background": "#d7af5f33",
        "scrollbar": "#353535",
        "scrollbar-hover": "#d7af5f",
        "scrollbar-active": "#d7875f",
        "link-color": "#5fafd7",
        "link-hover-color": "#5faf87",
        "footer-key-foreground": "#d0d0d0",
        "footer-key-background": "transparent",
        "footer-description-foreground": "#bdbdbd",
        "button-foreground": "#ffffff",
        "button-color-foreground": "#000000",
    },
)
