"""typed agent event payloads v2 — drop and recreate task_events

Alpha hard cut: the ``task_events`` table payload column previously stored
opaque ``dict[str, Any]`` payloads keyed against a ``SessionEventType`` enum.
The v2 shape stores the discriminated ``AgentEvent`` variant directly:
``event_type`` = variant ``kind`` string (lowercase), ``payload`` = full
``model_dump(mode="json")`` of the variant (includes ``kind`` field).

Existing event rows are dropped — this is accepted for the alpha track.

The migration is intentionally narrow: only ``task_events`` is touched.
All other autogenerated foreign-key / type changes that SQLite drift detection
flags are no-ops on this SQLite implementation and are intentionally excluded.

Downgrade restores the table structure but data is not recovered.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect as sa_inspect

revision = "5041f8573a34"
down_revision = "d0378306ab3d"
branch_labels = None
depends_on = None

_TABLE = "task_events"


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa_inspect(conn)

    # Drop the old table entirely — alpha hard cut, data loss accepted.
    if inspector.has_table(_TABLE):
        op.drop_table(_TABLE)

    # Recreate with the new payload shape.
    # ``event_type`` now stores the AgentEvent variant ``kind`` string.
    # ``payload`` stores the full model_dump(mode="json") of the variant.
    op.create_table(
        _TABLE,
        sa.Column("id", sa.String(), primary_key=True, nullable=False),
        sa.Column(
            "task_id",
            sa.String(),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "session_id",
            sa.String(),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
        sa.Column("event_type", sa.String(), nullable=False, index=True),
        sa.Column("payload", sa.JSON(), nullable=True, server_default=sa.text("'{}'")),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa_inspect(conn)
    if inspector.has_table(_TABLE):
        op.drop_table(_TABLE)

    # Restore original structure (data is not recovered).
    op.create_table(
        _TABLE,
        sa.Column("id", sa.String(), primary_key=True, nullable=False),
        sa.Column(
            "task_id",
            sa.String(),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "session_id",
            sa.String(),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
        sa.Column("event_type", sa.String(), nullable=False, index=True),
        sa.Column("payload", sa.JSON(), nullable=True, server_default=sa.text("'{}'")),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
