"""add task_type and agent_role fields for multi-dimensional analytics"""

revision = '6cbe15d02de6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('agent_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('sessions', 'cost_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_index(op.f('ix_sessions_mode'), table_name='sessions')
    op.create_index(op.f('ix_sessions_agent_role'), 'sessions', ['agent_role'], unique=False)
    op.drop_column('sessions', 'mode')
    op.alter_column('task_events', 'event_type',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('OUTPUT_CHUNK', 'AGENT_STATUS', 'TOOL_CALL_START', 'TOOL_CALL_UPDATE', 'AGENT_COMPLETED', 'AGENT_FAILED', 'PLAN_UPDATE', 'TASK_STATUS_CHANGED', 'MERGE_COMPLETED', 'MERGE_FAILED', 'CRITERION_VERDICT', 'AUTO_REVIEW_STARTED', 'INSIGHT_EXTRACTED', 'STEP_VERIFIED', 'CHECKPOINT_CREATED', 'SESSION_REWOUND', 'HOOK_BLOCKED', 'COMPACTION_TRIGGERED', name='sessioneventtype'),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_foreign_key(None, 'tasks', 'repos', ['repo_id'], ['id'])
    op.drop_column('tasks', 'execution_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('execution_mode', sa.VARCHAR(length=4), nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_column('tasks', 'task_type')
    op.alter_column('task_events', 'event_type',
               existing_type=sa.Enum('OUTPUT_CHUNK', 'AGENT_STATUS', 'TOOL_CALL_START', 'TOOL_CALL_UPDATE', 'AGENT_COMPLETED', 'AGENT_FAILED', 'PLAN_UPDATE', 'TASK_STATUS_CHANGED', 'MERGE_COMPLETED', 'MERGE_FAILED', 'CRITERION_VERDICT', 'AUTO_REVIEW_STARTED', 'INSIGHT_EXTRACTED', 'STEP_VERIFIED', 'CHECKPOINT_CREATED', 'SESSION_REWOUND', 'HOOK_BLOCKED', 'COMPACTION_TRIGGERED', name='sessioneventtype'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.add_column('sessions', sa.Column('mode', sa.VARCHAR(length=4), nullable=False))
    op.drop_index(op.f('ix_sessions_agent_role'), table_name='sessions')
    op.create_index(op.f('ix_sessions_mode'), 'sessions', ['mode'], unique=False)
    op.alter_column('sessions', 'cost_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_column('sessions', 'agent_role')
    # ### end Alembic commands ###
