#!/usr/bin/env python3
"""Generate TypeScript interfaces from the response-model JSON schemas.

Reads the Pydantic ``model_json_schema()`` output for every model in
``src/kagan/server/responses.py`` and emits a single ``.ts`` file with
matching TypeScript interfaces.

Usage:
    python scripts/generate_wire_types.py            # writes to stdout
    python scripts/generate_wire_types.py -o FILE    # writes to FILE
    python scripts/generate_wire_types.py --check    # exits 1 if FILE differs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the project source is importable when running from repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from kagan.server.responses import RESPONSE_MODELS  # noqa: E402


# ── JSON-Schema → TypeScript mapper ─────────────────────────────────────────


def _ts_type(schema: dict, defs: dict) -> str:  # noqa: C901
    """Convert a JSON-Schema property spec to a TypeScript type string."""
    # Handle $ref
    if "$ref" in schema:
        ref = schema["$ref"].rsplit("/", 1)[-1]
        return ref

    # Handle anyOf (Pydantic's way of expressing Optional / union)
    if "anyOf" in schema:
        variants = [_ts_type(v, defs) for v in schema["anyOf"] if v.get("type") != "null"]
        has_null = any(v.get("type") == "null" for v in schema["anyOf"])
        base = " | ".join(variants) if variants else "unknown"
        return f"{base} | null" if has_null else base

    schema_type = schema.get("type")
    if schema_type == "string":
        # Literal enum
        if "enum" in schema:
            return " | ".join(f"'{v}'" for v in schema["enum"])
        return "string"
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        items = schema.get("items", {})
        return f"{_ts_type(items, defs)}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if additional and isinstance(additional, dict):
            return f"Record<string, {_ts_type(additional, defs)}>"
        return "Record<string, unknown>"
    if schema_type == "null":
        return "null"

    return "unknown"


def _generate_definition(name: str, schema: dict, defs: dict) -> list[str]:
    """Generate lines for a single TypeScript definition.

    Pure enum schemas (no properties) become type aliases; object schemas
    become interfaces; schemas that extend another become interface extends.
    """
    lines: list[str] = []

    # Pure enum schema — emit as string type alias.
    # Both StrEnum and IntEnum are serialized as strings on the wire (StrEnum values,
    # IntEnum names).  Downstream code in types.ts can re-export narrower unions.
    schema_type = schema.get("type")
    if "enum" in schema and "properties" not in schema and "allOf" not in schema:
        lines.append(f"export type {name} = string;")
        return lines

    # Object schema (interface)
    extends_name = None
    props: dict = {}
    required: set[str] = set()

    if "allOf" in schema:
        for entry in schema["allOf"]:
            if "$ref" in entry:
                extends_name = entry["$ref"].rsplit("/", 1)[-1]
            if "properties" in entry:
                props.update(entry["properties"])
                required.update(entry.get("required", []))
    else:
        props = schema.get("properties", {})
        required = set(schema.get("required", []))

    extends_clause = f" extends {extends_name}" if extends_name else ""
    lines.append(f"export interface {name}{extends_clause} {{")

    for field_name, field_schema in props.items():
        ts = _ts_type(field_schema, defs)
        optional = field_name not in required
        opt_mark = "?" if optional else ""
        lines.append(f"  {field_name}{opt_mark}: {ts};")

    lines.append("}")
    return lines


def generate_ts(*, include_header: bool = True) -> str:
    """Return full TypeScript source for all response models."""
    # Collect all schemas in a combined $defs dict
    all_defs: dict[str, dict] = {}
    root_order: list[str] = []

    for name, model in RESPONSE_MODELS.items():
        schema = model.model_json_schema(mode="serialization")
        # Gather nested $defs
        for def_name, def_schema in schema.get("$defs", {}).items():
            all_defs[def_name] = def_schema
        # The root schema itself
        all_defs[name] = schema
        root_order.append(name)

    # Determine emission order: $defs first (deps), then roots
    emitted: set[str] = set()
    output_lines: list[str] = []

    if include_header:
        output_lines.extend([
            "/**",
            " * AUTO-GENERATED by scripts/generate_wire_types.py",
            " * DO NOT EDIT — regenerate with: uv run python scripts/generate_wire_types.py -o packages/web/src/lib/api/generated-wire-types.ts",
            " */",
            "",
        ])

    # Emit dependency defs first
    for name in list(all_defs):
        if name not in root_order and name not in emitted:
            output_lines.extend(_generate_definition(name, all_defs[name], all_defs))
            output_lines.append("")
            emitted.add(name)

    # Emit root models in declaration order
    for name in root_order:
        if name not in emitted:
            output_lines.extend(_generate_definition(name, all_defs[name], all_defs))
            output_lines.append("")
            emitted.add(name)

    return "\n".join(output_lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate TypeScript from response models")
    parser.add_argument("-o", "--output", type=Path, help="Output file path")
    parser.add_argument("--check", action="store_true", help="Check mode: exit 1 if file differs")
    args = parser.parse_args()

    ts_source = generate_ts()

    if args.check:
        if args.output is None:
            print("ERROR: --check requires -o FILE", file=sys.stderr)
            return 1
        if not args.output.exists():
            print(f"DRIFT: {args.output} does not exist")
            return 1
        existing = args.output.read_text()
        if existing != ts_source:
            print(f"DRIFT: {args.output} is out of date. Regenerate with:")
            print(f"  uv run python scripts/generate_wire_types.py -o {args.output}")
            return 1
        print(f"OK: {args.output} is up to date")
        return 0

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(ts_source)
        print(f"Wrote {args.output}")
    else:
        print(ts_source, end="")

    return 0


if __name__ == "__main__":
    sys.exit(main())
